export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
export const SELECT_SECTION = 'SELECT_SECTION';
export const TOGGLE_SHOW_VIRAL = 'TOGGLE_SHOW_VIRAL';
export const SELECT_SORT = 'SELECT_SORT';
export const SELECT_WINDOW = 'SELECT_WINDOW';